# Generated by Django 3.1.3 on 2021-01-19 04:14

from django.conf import settings
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import setup_apikey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKEY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ex_id', models.CharField(choices=[('BIN', 'Binance'), ('BIM', 'Binance Margin'), ('BIF', 'Binance Future'), ('HIT', 'Hitbtc'), ('KRA', 'Kraken'), ('DAX', 'Indodax'), ('HUO', 'Huobi'), ('KEX', 'Okex3'), ('KUC', 'Kucoin'), ('MOX', 'Moonix')], default='BIN', max_length=3)),
                ('api_keys', models.TextField()),
                ('secret_keys', models.TextField()),
                ('passphrase', models.TextField(blank=True)),
                ('exclude_pnl', models.BooleanField(default=False)),
                ('added_by', models.CharField(blank=True, default=18, max_length=100)),
                ('tags', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('own_name', models.ForeignKey(blank=True, null=True, on_delete=models.SET(setup_apikey.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
