DATABASE_SRV = ''
DATABASE_PORT = 27017
DATABASE_USERNAME = ''
DATABASE_PASSWD = ''
DATABASE_NAM = ''

FANSIPAN_DB = 'localhost'
FANSIPAN_DB_PORT = 27017
FANSIPAN_DB_USERNAME = 'myAdmin'
FANSIPAN_DB_PASSWD = 'abc123321'

EX_LIST = ['BIN', 'BIM', 'BIF', 'HIT', 'KRA', 'DAX', 'HUO', 'KEX', 'KUC', 'MOX']
