# Generated by Django 3.1.3 on 2021-01-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotInstancesMax',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avg_tool_bots_max', models.IntegerField(default=1)),
                ('support_big_amount_bots_max', models.IntegerField(default=1)),
                ('support_trailing_stop_bots_max', models.IntegerField(default=1)),
                ('arb_two_way_bots_max', models.IntegerField(default=1)),
                ('atr_trailing_stop_bots_max', models.IntegerField(default=1)),
                ('two_way_sp_tool_bots_max', models.IntegerField(default=1)),
                ('support_multi_box_bots_max', models.IntegerField(default=1)),
                ('bs_sb_continuously_bots_max', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserBotInstancesRunning',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avg_tool_bots_running', models.IntegerField(default=0)),
                ('support_big_amount_bots_running', models.IntegerField(default=0)),
                ('support_trailing_stop_bots_running', models.IntegerField(default=0)),
                ('arb_two_way_bots_running', models.IntegerField(default=0)),
                ('atr_trailing_stop_bots_running', models.IntegerField(default=0)),
                ('two_way_sp_tool_bots_running', models.IntegerField(default=0)),
                ('support_multi_box_bots_running', models.IntegerField(default=0)),
                ('bs_sb_continuously_tool_bots_running', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avg_tool', models.BooleanField(default=False)),
                ('support_big_amount_bot', models.BooleanField(default=False)),
                ('support_trailing_stop_bot', models.BooleanField(default=False)),
                ('arb_twoway_tool', models.BooleanField(default=False)),
                ('atr_trailing_stop_bot_tool', models.BooleanField(default=False)),
                ('two_way_sp_tool', models.BooleanField(default=False)),
                ('support_multi_box', models.BooleanField(default=False)),
                ('bs_sb_continuously_tool', models.BooleanField(default=False)),
            ],
        ),
    ]
