# Generated by Django 3.1.3 on 2021-01-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_twofa',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('countrycode', models.TextField()),
                ('mobile_number', models.TextField()),
                ('secret_key_otp', models.TextField()),
                ('two_fa_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
