# Generated by Django 3.1.3 on 2021-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwoFA_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_twofa',
            name='secret_key_google',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='user_twofa',
            name='countrycode',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='user_twofa',
            name='mobile_number',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='user_twofa',
            name='secret_key_otp',
            field=models.TextField(default='na'),
        ),
    ]
